Added test coverage for check-release-stable action.

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -564,6 +564,12 @@ jobs:
 
   test-check-release-is-stable-ok:
     runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        release-tag:
+          - "2026-08-25"  # stable, latest
+          - "2026-07-10"  # stable, non latest
     steps:
       - uses: actions/checkout@v6
       - name: Check
@@ -571,10 +577,17 @@ jobs:
         with:
           # Frozen repo, known to be stable.
           release-repo: fpgawars/apio-examples
-          release-tag: 2026-08-25
+          release-tag: ${{ matrix.release-tag }}
 
   test-check-release-is-stable-not-ok:
     runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        release-tag:
+          # TODO: Add a case for a draft.
+          - "2026-08-24"  # pre release
+          - "2026-07-11"  # Does not exist
     steps:
       - uses: actions/checkout@v6
       - name: Check
@@ -584,9 +597,9 @@ jobs:
         with:
           # Frozen repo, known to be pre-release.
           release-repo: fpgawars/apio-examples
-          release-tag: 2026-08-24
+          release-tag: ${{ matrix.release-tag }}
       - name: Assert check failed
         if: steps.check.outcome == 'success'
         run: |
-          echo "expected to fail" >&2
+          echo "Expected ${{ matrix.release-tag }} to fail" >&2
           exit 1
