Added a workflow action check-release-stable

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -561,3 +561,32 @@ jobs:
         run: |
           echo "expected ${{ matrix.release-tag }} to fail" >&2
           exit 1
+
+  test-check-release-is-stable-ok:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v6
+      - name: Check
+        uses: ./.github/actions/check-release-is-stable
+        with:
+          # Frozen repo, known to be stable.
+          repo-tag: fpgawars/apio-examples
+          release-tag: 2026-08-25
+
+  test-check-release-is-stable-not-ok:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v6
+      - name: Check
+        id: check
+        continue-on-error: true
+        uses: ./.github/actions/check-release-is-stable
+        with:
+          # Frozen repo, known to be pre-release.
+          repo-tag: fpgawars/apio-examples
+          release-tag: 2026-08-24
+      - name: Assert check failed
+        if: steps.check.outcome == 'success'
+        run: |
+          echo "expected to fail" >&2
+          exit 1
